version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: d3
    versions:
    - 6.5.0
    - 6.6.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: lodash.mergewith
    versions:
    - 4.6.2
